"""Canonical table profiles — cross-document structure constraints.

FIPS 140-3 Security Policies, though authored independently, share a small set of
mandated tables with predictable columns (SSP/CSP tables, services tables, ports
tables, algorithm tables, self-tests, ...). We declare those shared shapes once,
then use them to (a) *recognize* a table regardless of vendor wording, (b) *map*
its columns to canonical field names so the data is queryable, and (c) *validate*
the extraction by reporting which expected columns were found vs. missing.

Each profile field lists the header keyword(s) that identify it. A field spec is
either a list of positive keywords, or a dict ``{"kw": [...], "not": [...]}`` —
the ``not`` list are negative keywords that *prevent* a match, which stops
adjacent similar columns from cross-mapping (e.g. keeping "Strength" from being
claimed by the "Security Function" column).

``coreFields`` are the columns a genuine instance of the table must have; they
drive the honest confidence metric (see match_profile → coreCoverage) so that a
table which legitimately has few columns is not scored as low-confidence.
"""
from __future__ import annotations

import re

TABLE_PROFILES = [
    {
        "type": "sensitiveSecurityParameter",
        "collection": "sensitiveSecurityParameters",
        "captionHint": r"(sensitive security parameter|\bssp\b|\bcsp\b)",
        "minFields": 3,
        "requiredFields": ["name"],
        "coreFields": ["name"],
        "expectedColumns": {
            "name":            {"kw": ["name", "ssp", "csp", "key"], "not": ["function", "type"]},
            # Block `type` only from the NAME column ("Key/CSP Name", "SSP Name") —
            # 140-2 tables label the type column "Key / CSP Type", which the old
            # csp/key/ssp negatives wrongly suppressed. `name` gets the negative
            # `type` so "Key/CSP Name" and "Key/CSP Type" can't both grab it.
            "type":            {"kw": ["type"], "not": ["name"]},
            # `description` before `use` so "Description and Usage" (a common 140-2
            # SSP column) maps to description rather than being claimed by 'usage'.
            "description":     {"kw": ["description"], "not": ["name"]},
            "strength":        {"kw": ["strength", "size", "length", "bits"], "not": ["function", "use"]},
            "securityFunction":["security function", "function and", "cert"],
            "generation":      ["generation", "generated", "generated by"],
            "establishment":   ["establish", "agreement", "transport"],
            "storageLocation": ["storage location", "location"],
            "storage":         ["storage", "stored", "storage method"],
            "zeroization":     ["zeroiz", "destruction"],
            "use":             {"kw": ["use", "usage", "related key", "used by"], "not": ["function", "description"]},
            "role":            {"kw": ["available to role", "role"], "not": ["name", "type"]},
            "input":           ["input"],
            "output":          ["output"],
            "access":          ["access"],
            "importExport":    ["import", "export"],
        },
    },
    {
        "type": "service",
        "collection": "services",
        "captionHint": r"(approved services|non-approved services|roles.*service|service commands)",
        # 140-2 service tables are frequently just Service|Description (2 cols); a
        # minFields of 3 dropped them entirely. 2 is safe because the `name` column
        # must still carry "service"/"name" and ranking prefers the best profile.
        "minFields": 2,
        "requiredFields": ["name"],
        "coreFields": ["name"],
        "expectedColumns": {
            "name":              {"kw": ["service", "name"], "not": ["function"]},
            "description":       ["description"],
            "roles":             ["role"],
            # per-role access columns of a 140-2 service/role matrix (CO|User|World…)
            "roleAccess":        {"kw": ["crypto officer", "cryptographic officer", "co ", "user", "world", "operator", "officer"], "not": ["service", "name", "description"]},
            # cspsAccessed BEFORE approvedFunctions so a "CSP / Algorithm" column
            # maps to CSPs (via 'csp') rather than being claimed by 'algorithm'
            "cspsAccessed":      ["csp", "ssp access", "ssp", "keys"],
            "approvedFunctions": {"kw": ["approved security function", "algorithm", "function"], "not": ["service"]},
            "access":            ["access", "rights", "permission"],
            "indicator":         ["indicator", "status"],
            "type":              {"kw": ["type"], "not": ["service", "key"]},
            "properties":        ["properties"],
            "input":             ["input", "command"],
            "output":            ["output"],
        },
    },
    {
        "type": "portsAndInterfaces",
        "collection": "portsAndInterfaces",
        "captionHint": r"(ports and interfaces|physical port|logical interface)",
        "minFields": 2,
        "requiredFields": [],
        "coreFields": ["logicalInterface"],
        "expectedColumns": {
            # 140-2 tables often pair "Physical Interface" with "FIPS 140-2 Logical
            # Interface"; without "physical interface" here only one column mapped
            # and the table fell below minFields.
            "physicalPort":     ["physical port", "physical interface", "port", "connector"],
            "logicalInterface": ["logical interface", "interface"],
            "dataThatPasses":   ["data", "description"],
        },
    },
    {
        "type": "approvedAlgorithm",
        "collection": "approvedAlgorithmsDetailed",
        "captionHint": r"(approved algorithm|approved security function|cavp)",
        "minFields": 2,
        "requiredFields": ["name"],
        "coreFields": ["name"],
        "expectedColumns": {
            "name":        {"kw": ["algorithm", "cipher", "primitive", "sfc"], "not": ["test"]},
            "cavpCert":    ["cavp", "cert", "validation"],
            "modeMethod":  ["mode", "method"],
            "keySize":     ["key size", "size", "strength", "length", "curve"],
            "properties":  ["properties"],
            "useFunction": ["use", "caveat", "function"],
            "reference":   ["reference", "standard"],
            "description": ["description"],
        },
    },
    {
        "type": "selfTest",
        "collection": "selfTests",
        "captionHint": r"(self-?test|pre-?operational|conditional test|periodic)",
        "minFields": 3,
        "requiredFields": [],
        "coreFields": ["algorithmOrTest"],
        "expectedColumns": {
            "algorithmOrTest": ["algorithm", "test"],
            "testMethod":      ["method"],
            "testType":        ["test type", "type"],
            "period":          ["period"],
            "periodicMethod":  ["periodic"],
            "details":         ["details", "description"],
        },
    },
    {
        "type": "moduleConfiguration",
        "collection": "moduleConfigurations",
        "captionHint": r"(tested configuration|operating system|hardware.*firmware version|distinguishing)",
        "minFields": 2,
        "requiredFields": [],
        "coreFields": [],
        "expectedColumns": {
            "model":            ["model"],
            "operatingSystem":  ["operating system", "operating"],
            "hardwarePlatform": ["platform"],
            "hardwareVersion":  ["hardware", "part number"],
            "firmwareVersion":  ["firmware"],
            "softwareVersion":  {"kw": ["software", "version"], "not": ["hardware"]},
            "processor":        ["processor", "cpu"],
            "paaPai":           ["paa", "pai", "aes-ni", "aes ni"],
            "hypervisor":       ["hypervisor", "host os"],
            "features":         ["features"],
            "package":          ["package", "file name", "file"],
            "integrityTest":    ["integrity"],
            "distinguishing":   ["distinguishing"],
        },
    },
    {
        "type": "modeOfOperation",
        "collection": "modesOfOperation",
        "captionHint": r"(mode of operation|approved mode|non-approved mode|modes of operation)",
        "minFields": 3,
        "requiredFields": ["name"],
        "coreFields": ["name"],
        "expectedColumns": {
            "name":        {"kw": ["mode name", "mode", "name"], "not": ["service"]},
            "description": ["description"],
            "type":        ["type"],
            "indicator":   ["indicator", "status"],
        },
    },
    {
        # 140-2 roles/authentication table: Role | Type of Authentication |
        # Authentication Data (Strength). Distinct from the services table.
        "type": "roleAuthentication",
        "collection": "roleAuthentications",
        "captionHint": r"(roles and (required )?authentication|authentication (type|data|policy)|strength of authentication)",
        "minFields": 2,
        # Require BOTH role AND a genuine authentication column so this doesn't
        # steal a wide service/role-matrix table that merely has a "Role" column
        # (that mis-claim regressed 4850). Bare "type"/"data" are NOT auth signals.
        "requiredFields": ["role", "authenticationType"],
        "coreFields": ["role", "authenticationType"],
        "expectedColumns": {
            "role":               {"kw": ["role"], "not": ["type", "data", "service"]},
            "authenticationType": ["type of authentication", "authentication type", "authentication mechanism"],
            "authenticationData": ["authentication data"],
            "strength":           ["strength of authentication", "strength"],
        },
    },
    {
        "type": "acronyms",
        "collection": "acronyms",
        "captionHint": r"(acronym|abbreviation|definitions)",
        "minFields": 2,
        "requiredFields": [],
        "coreFields": ["term", "definition"],
        "expectedColumns": {
            "term":       ["acronym", "abbreviation", "term"],
            "definition": ["definition", "full", "specification", "meaning"],
        },
    },
    # ---- additional profiles from the mining backlog (suggested-profiles.json) ----
    {
        "type": "securityLevelTable",
        "collection": "securityLevelTable",
        "captionHint": r"(iso/?iec 24759|security level|fips 140-?3 section)",
        "minFields": 2,
        "requiredFields": ["level"],
        "coreFields": ["level"],
        "expectedColumns": {
            "isoSection":  ["iso", "24759", "section"],
            "requirement": ["fips", "title", "requirement", "area"],
            "level":       ["level"],
        },
    },
    {
        "type": "apiCall",
        "collection": "apiCalls",
        "captionHint": r"(api call|function call|c_ )",
        "minFields": 2,
        "requiredFields": ["call"],
        "coreFields": ["call"],
        "expectedColumns": {
            "call":        ["api call", "api", "call", "function"],
            "description": ["description", "purpose"],
            "service":     ["service"],
        },
    },
]

_PROFILE_BY_TYPE = {p["type"]: p for p in TABLE_PROFILES}


def _norm_cell(s: str) -> str:
    return re.sub(r"[^a-z0-9 ]+", " ", (s or "").lower())


def _spec(v):
    """Normalize a field spec to (positive_keywords, negative_keywords)."""
    if isinstance(v, dict):
        return v.get("kw", []), v.get("not", [])
    return v, []


def _cell_match(kw: str, cell: str, cell_ns: str) -> bool:
    # Match against the cell and a space-stripped variant, so words that
    # pdfplumber splits ("indicato r", "descriptio n") still match ("indicator").
    return kw in cell or kw.replace(" ", "") in cell_ns


def match_profile(header: list[str]) -> dict | None:
    """Best-matching profile for a header row, with the column map, score, the
    missing expected columns, and — crucially — coreCoverage (fraction of the
    table's *essential* columns that were found). coreCoverage is the honest
    confidence signal: a narrow-but-complete table scores 1.0 even if it lacks
    optional columns."""
    norm = [_norm_cell(c) for c in header]
    norm_ns = [c.replace(" ", "") for c in norm]
    best = None
    for prof in TABLE_PROFILES:
        mapping: dict[str, int] = {}
        used: set[int] = set()
        for field, spec in prof["expectedColumns"].items():
            pos, neg = _spec(spec)
            for i, cell in enumerate(norm):
                if i in used:
                    continue
                if any(_cell_match(k, cell, norm_ns[i]) for k in pos) and \
                   not any(_cell_match(k, cell, norm_ns[i]) for k in neg):
                    mapping[field] = i
                    used.add(i)
                    break
        if not all(r in mapping for r in prof["requiredFields"]):
            continue
        score = len(mapping)
        if score < prof["minFields"]:
            continue
        core = prof.get("coreFields", [])
        core_matched = sum(1 for f in core if f in mapping)
        core_cov = round(core_matched / len(core), 2) if core else 1.0
        # Rank by (core coverage, score) so the semantically-best profile wins.
        rank = (core_cov, score)
        if best is None or rank > best["_rank"]:
            best = {
                "type": prof["type"],
                "collection": prof["collection"],
                "mapping": mapping,
                "score": score,
                "expectedCount": len(prof["expectedColumns"]),
                "matchedColumns": list(mapping.keys()),
                "missingExpected": [f for f in prof["expectedColumns"] if f not in mapping],
                "coreFields": core,
                "coreCoverage": core_cov,
                "_rank": rank,
            }
    if best:
        best.pop("_rank", None)
    return best


_CERT_CELL_RE = re.compile(r"^#?\s*[AC]\d{2,5}$")
_STD_REF_RE = re.compile(r"\b(?:fips|sp)\s*-?\s*\d{2,4}", re.IGNORECASE)
_ALGO_TOKENS = ("aes", "sha", "hmac", "rsa", "ecdsa", "dsa", "drbg", "kbkdf",
                "kdf", "kas", "kts", "ecdh", "cmac", "gcm", "gmac", "xts", "ctr",
                "tdes", "triple-des", "ml-kem", "ml-dsa", "slh-dsa", "hash", "kmac")


def _looks_algo(cell: str) -> bool:
    low = cell.lower()
    return bool(_STD_REF_RE.search(cell)) or any(t in low for t in _ALGO_TOKENS)


def content_profile(rows: list[list[str]]) -> dict | None:
    """Recognize an algorithm-detail table by its CONTENT when no header matched.

    Many Security Policies present the algorithm table with a detached or missing
    header (the PDF parser drops it), leaving an obviously-tabular body: a column
    of ACVP cert labels (#C1925 / A3548) beside a column of algorithm names with
    FIPS/SP references. We detect those columns directly and synthesize an
    ``approvedAlgorithm`` mapping so the rows still type cleanly.
    """
    body = [r for r in rows if any((c or "").strip() for c in r)]
    if len(body) < 2:
        return None
    ncols = max(len(r) for r in body)
    cols = [[(r[i] if i < len(r) else "").strip() for r in body] for i in range(ncols)]

    def frac(col, pred):
        nz = [c for c in col if c]
        return sum(1 for c in nz if pred(c)) / len(nz) if nz else 0.0

    cert_idx = next((i for i, c in enumerate(cols)
                     if frac(c, lambda x: bool(_CERT_CELL_RE.match(x))) >= 0.5), None)
    name_scores = sorted(((frac(c, _looks_algo), i) for i, c in enumerate(cols) if i != cert_idx),
                         reverse=True)
    if not name_scores or name_scores[0][0] < 0.5:
        return None
    name_idx = name_scores[0][1]
    mapping = {"name": name_idx}
    if cert_idx is not None:
        mapping["cavpCert"] = cert_idx
    for i, c in enumerate(cols):  # label the remaining columns by content
        if i in mapping.values():
            continue
        blob = " ".join(c).lower()
        if any(w in blob for w in ("bit", "key size", "strength", "curve", "modulus")):
            mapping.setdefault("keySize", i)
        elif any(w in blob for w in ("encrypt", "decrypt", "sign", "verif", "generation",
                                     "authentication", "derivation", "agreement", "wrap")):
            mapping.setdefault("useFunction", i)
        elif any(w in blob for w in ("counter", "feedback", "mode", "cbc", "ecb", "ofb")):
            mapping.setdefault("modeMethod", i)
    if len(mapping) < 2:
        return None
    return {"type": "approvedAlgorithm", "collection": "approvedAlgorithmsDetailed",
            "mapping": mapping, "score": len(mapping), "expectedCount": 8,
            "matchedColumns": list(mapping), "missingExpected": [],
            "coreFields": ["name"], "coreCoverage": 1.0, "byContent": True}


def map_row(match: dict, header: list[str], row: list[str], source: dict) -> dict:
    """Map a data row to canonical fields per the matched profile. Unmapped but
    non-empty cells are retained under `extraColumns` so nothing is dropped."""
    width = len(header)
    cells = (row + [""] * width)[:width]
    mapping = match["mapping"]
    obj: dict = {}
    for field, idx in mapping.items():
        v = cells[idx].strip()
        if v:
            obj[field] = v
    if not obj.get("name"):
        obj["name"] = next((c for c in cells if c.strip()), "")
    mapped_idx = set(mapping.values())
    extra = {}
    for i, c in enumerate(cells):
        if i not in mapped_idx and c.strip():
            key = (header[i] or f"col{i}").strip() or f"col{i}"
            extra[key] = c.strip()
    if extra:
        obj["extraColumns"] = extra
    obj["source"] = source
    return obj
