#!/usr/bin/env python3
"""Review-risk graph: turn a normalized record into a reviewer's worksheet.

The graph has four tiers — Clue -> Inference -> Risk -> Evidence-to-close. Only
the FIRST tier is produced here, and it is fully DETERMINISTIC: each clue is
grounded in fields already in the record (firmware/bootloader versions, services,
ports/interfaces, protocols, algorithms, runtime) plus a keyword scan of the
verbatim sidecar text, and every clue carries its evidence so it is auditable.

The Inference/Risk/Evidence tiers are security *reasoning*, not extraction. They
are generated by a higher-capability model that reasons over this structured clue
set (never the raw PDF), and — critically — are framed as review questions and
evidence gaps, NOT as vulnerability findings. `build_prompt()` encodes that
contract; wiring the model call is the same gated pattern as ai_extract.py.

    python review_graph.py records/4703.json              # deterministic clue set
    python review_graph.py records/4703.json --mermaid    # clue tier as Mermaid
    python review_graph.py records/4703.json --prompt     # model prompt for tiers 2-4
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys

# Each clue category: id, human label, and how to detect it from the record.
# Detection is deterministic and always reports the evidence it fired on.
_UPDATE_KW = re.compile(r"\b(update|upgrade|downgrade|firmware load|load firmware|recovery|rollback)\b", re.I)
_UNAUTH_KW = re.compile(r"\b(unauthenticated|un-?auth|without authentication|no authentication|self-?test|show status|status output)\b", re.I)
_IFACE_KW = ("usb", "uart", "ftdi", "smbus", "rj45", "jtag", "serial", "i2c", "spi", "pcie")
_PROTO_KW = ("tls", "ssh", "ikev", "ipsec", "https", "dtls")
_TLS_LIBS = ("openssl", "wolfssl", "mbedtls", "boringssl", "gnutls", "nss")
_RUNTIME_KW = ("operating system", "linux", "kernel", "arm trusted firmware", "u-boot", "uboot", "bootloader", "application")


def _sidecar_text(record, path):
    side = (record.get("securityPolicy") or {}).get("rawText", {}).get("sidecarFile")
    if side:
        p = os.path.join(os.path.dirname(os.path.abspath(path)), side)
        if os.path.exists(p):
            return open(p, encoding="utf-8", errors="replace").read()
    return ""


def extract_clues(record: dict, text: str = "") -> list[dict]:
    sp = record.get("securityPolicy") or {}
    cert = record.get("certificate", {})
    low = text.lower()
    clues: list[dict] = []

    def add(cid, label, evidence, source, confidence):
        if evidence:
            clues.append({"id": cid, "label": label, "evidence": evidence[:8],
                          "source": source, "confidence": confidence})

    # Confidence is deterministic and provenance-based (NOT a model judgement):
    #   high   = derived from a structured record field (firmware list, services, ports)
    #   low    = a bare keyword hit in the verbatim text (context not verified)
    # This is what lets a reviewer trust C1/C2/C4 more than C5/C6.

    # C1 — boot chain / firmware provenance (structured field)
    fw = cert.get("firmwareVersions", [])
    boot = [f.get("raw", "") for f in fw if re.search(r"boot|uboot|u-boot", json.dumps(f), re.I)]
    if fw:
        add("C1", "Firmware / bootloader versions disclosed (identity, not provenance)",
            boot or [f.get("raw", "") for f in fw], "certificate.firmwareVersions", "high")

    # C2 — firmware update / rollback surface
    upd = [s.get("name", "") for s in sp.get("services", []) if _UPDATE_KW.search(json.dumps(s))]
    if upd:
        add("C2", "Firmware update / recovery / rollback services", upd,
            "securityPolicy.services", "high")
    elif _UPDATE_KW.search(low):
        add("C2", "Firmware update / recovery / rollback (referenced in text)",
            [m.group(0) for m in list(_UPDATE_KW.finditer(text))[:5]], "text:keyword", "low")

    # C3 — pre-auth / unauthenticated API surface. Only services that EXPLICITLY
    # signal no-auth / self-test / status (a missing role field is a profile gap,
    # not evidence of pre-auth reachability, so it is deliberately not used here).
    unauth = [s.get("name", "") for s in sp.get("services", []) if _UNAUTH_KW.search(json.dumps(s))]
    if unauth:
        add("C3", "Unauthenticated / self-test / status service surface", unauth,
            "securityPolicy.services", "high")
    elif _UNAUTH_KW.search(low):
        add("C3", "Self-test / status surface (referenced in text)",
            [m.group(0) for m in list(_UNAUTH_KW.finditer(text))[:5]], "text:keyword", "low")

    # C4 — physical / logical interfaces (incl. ones 'blocked in firmware')
    ports = [(p.get("name") or p.get("port") or "") for p in sp.get("portsAndInterfaces", [])]
    iface = [p for p in ports if any(k in p.lower() for k in _IFACE_KW)]
    blocked = [ln.strip()[:60] for ln in text.splitlines() if "blocked in firmware" in ln.lower()][:5]
    if iface or blocked:
        add("C4", "Physical/logical interfaces (some 'blocked in firmware')", iface + blocked,
            "securityPolicy.portsAndInterfaces" if iface else "text:blocked-in-firmware",
            "high" if iface else "medium")

    # C5 — protocol / secure-channel references. NOTE: these are keyword hits and
    # are frequently KDF algorithm names (TLS/SSH/IKE KDFs) rather than a live
    # channel the module operates — hence 'low' confidence and cautious wording.
    protos = [k.upper() for k in _PROTO_KW if k in low]
    libs = [k for k in _TLS_LIBS if k in low]
    if protos:
        ev = protos + [f"library named: {l}" for l in libs]
        ev += ["no library/version identified"] if not libs else []
        add("C5", "Protocol / secure-channel references (may be KDF names, not a live channel)",
            ev, "text:keyword", "low")

    # C6 — runtime / OS reference. Soft by construction: a keyword match does not
    # establish that the OS is inside the cryptographic boundary.
    runtime = [k for k in _RUNTIME_KW if k in low]
    if any(k in low for k in ("operating system", "linux", "kernel", "application")):
        add("C6", "Operating system / runtime referenced (boundary membership not asserted)",
            runtime, "text:keyword", "low")

    return clues


# --- evidence normalization (reviewer-facing, not the audit sidecar) ----------
# Raw evidence samples are verbatim cells: a firmware config enumerates the full
# FW×bootloader cartesian product, pdftotext splits identifiers ("KEY_INI T"),
# and near-duplicate version strings repeat. For the diagram we collapse version
# suffixes to a family glob, repair short split tails, and dedupe — the verbatim
# values remain in the record; only the picture is normalized.
_VER_TAIL = re.compile(r"([:\-])\d[\w.]*(?:[-.]\w+)+")   # -10.23-1107-R02-SB, :10.23-1107


def _family(tok: str) -> str:
    return _VER_TAIL.sub(lambda m: m.group(1) + "*", tok)


def _repair_split(s: str) -> str:
    # rejoin a 1–2 char uppercase tail pdftotext split off an identifier
    # ("..._KEY_INI T" -> "..._KEY_INIT"); conservative so distinct ALLCAPS
    # service names separated by a space are left apart.
    return re.sub(r"\b([A-Z][A-Z0-9_]*[A-Z0-9])\s+([A-Z]{1,2})\b(?!_)", r"\1\2", s)


def normalize_evidence(evidence: list[str], limit: int = 3) -> list[str]:
    out, seen = [], set()
    for e in evidence:
        e = _repair_split(re.sub(r"\s+", " ", (e or "")).strip())
        e = " ".join(_family(t) for t in e.split(" "))
        e = re.sub(r'[\"<>]', "", e).replace("&", "and")
        if len(e) > 52:
            e = e[:51].rsplit(" ", 1)[0] + "…"
        key = e.lower()
        if e and key not in seen:
            seen.add(key)
            out.append(e)
        if len(out) >= limit:
            break
    return out


_CLUE_CLASS = {"high": "clueHigh", "medium": "clueMedium", "low": "clueLow"}
_CLUE_STYLES = [
    "classDef clueHigh fill:#eef3f9,stroke:#2f6fb0,stroke-width:2px,color:#1f3a5f;",
    "classDef clueMedium fill:#eef3f9,stroke:#6f7f91,color:#1f3a5f;",
    "classDef clueLow fill:#f7f7f7,stroke:#999,stroke-dasharray:4 4,color:#444;",
]


def to_mermaid_cluetier(module: str, clues: list[dict]) -> str:
    lines = ["flowchart LR",
             f"  %% Deterministic clue tier for {module}",
             "  %% confidence: high = structured record field; medium = structured but soft;"
             " low (dashed) = bare keyword hit, context unverified",
             '  subgraph CMVP["CMVP-disclosed clues (deterministic)"]']
    for c in clues:
        ev = "<br/>".join(normalize_evidence(c["evidence"]))
        tag = f'[{c.get("confidence", "?")}] '
        lines.append(f'    {c["id"]}["{tag}{c["label"]}<br/><i>{ev}</i><br/>src: {c.get("source","")}"]')
    lines.append("  end")
    lines += ["  " + s for s in _CLUE_STYLES]
    by_class: dict[str, list[str]] = {}
    for c in clues:
        by_class.setdefault(_CLUE_CLASS.get(c.get("confidence"), "clueMedium"), []).append(c["id"])
    for cls, ids in by_class.items():
        lines.append(f"  class {','.join(ids)} {cls};")
    return "\n".join(lines)


# --- deterministic review lanes (baseline 4-tier, no model call) --------------
# Category-generic inference/risk/evidence keyed to the clue CATEGORY (C1..C6),
# NOT to a specific document — so these generalize across vendors. They are review
# PROMPTS and evidence gaps, never findings. A capable-model pass (--graph) may
# later REFINE these into document-specific wording; this is the always-available
# floor so the reviewer surface is never clue-only.
_LANE_TEMPLATES = {
    "C1": {"inference": "Component identity is disclosed, but provenance and patch lineage are not.",
           "risk": "Do the vendor version strings obscure the upstream baseline, fork lineage, or known-CVE exposure?",
           "evidence": ["SBOM / component baselines", "patch and backport manifest", "CVE disposition"]},
    "C2": {"inference": "Trusted code is reachable through update and recovery paths.",
           "risk": "Are update images authenticated before parsing, and are downgrade/rollback paths constrained?",
           "evidence": ["update image format", "signature-before-parse proof", "anti-rollback / downgrade policy"]},
    "C3": {"inference": "Some services may process input before, or without, operator authentication.",
           "risk": "Can unauthenticated services leak state, consume resources, or transition security state?",
           "evidence": ["pre-auth reachability matrix", "rate limits and output redaction", "abuse-case tests"]},
    "C4": {"inference": "Interface reachability may vary by boot stage and lifecycle state.",
           "risk": "Are interfaces blocked before the bootloader runs, or only after approved mode starts?",
           "evidence": ["lifecycle reachability matrix", "boot-stage interface timing", "factory/recovery/error-state access controls"]},
    "C5": {"inference": "A protocol is referenced, but whether it is a live channel or only a KDF/algorithm name is unconfirmed.",
           "risk": "If a live TLS/SSH/IKE channel exists, could library CVEs apply, or is this only a KDF/documentation name?",
           "evidence": ["library identity & version", "certificate-validation behaviour", "protocol-CVE disposition"]},
    "C6": {"inference": "A runtime/OS is referenced, but its membership in the cryptographic boundary is not established.",
           "risk": "If the OS/runtime is in-boundary, could its CVEs be hidden by firmware-only versioning?",
           "evidence": ["runtime identity and config", "kernel/runtime hardening profile", "patch/backport manifest"]},
}


def build_review_lanes(clues: list[dict]) -> list[dict]:
    """Deterministic Clue→Inference→Risk→Evidence lanes. For a low-confidence clue
    the first evidence item becomes 'confirm the disclosure itself', honouring the
    same contract as build_prompt (don't escalate a bare keyword hit)."""
    lanes = []
    for c in clues:
        t = _LANE_TEMPLATES.get(c["id"])
        if not t:
            continue
        ev = list(t["evidence"])
        infer = t["inference"]
        if c.get("confidence") == "low":
            ev = ["confirm the disclosure itself (keyword hit, context unverified)"] + ev
            infer = "Possible only, " + infer[0].lower() + infer[1:]
        lanes.append({"n": c["id"][1:], "clue": c, "inference": infer,
                      "risk": t["risk"], "evidence": ev})
    return lanes


def _node(text: str) -> str:
    # strip Mermaid-breaking chars; '&' is dropped to 'and' (Mermaid parses label
    # text as HTML, so a bare '&' can be read as an entity start)
    return re.sub(r'[\"<>]', "", re.sub(r"\s+", " ", text)).replace("&", "and").strip()


def to_mermaid_lanes(module: str, clues: list[dict]) -> str:
    """Deterministic full 4-tier graph. Structurally identical to the model-pass
    output (Cn→In→Rn→En) so it passes validate_graph and renders the same way."""
    lanes = build_review_lanes(clues)
    if not lanes:
        return ""
    L = ["flowchart LR",
         f"  %% Deterministic review-risk graph for {module}",
         "  %% Review prompts and evidence gaps, NOT vulnerability findings.",
         '  subgraph CMVP["CMVP-disclosed clues"]']
    for x in lanes:
        c = x["clue"]
        ev = "<br/>".join(normalize_evidence(c["evidence"]))
        L.append(f'    C{x["n"]}["[{c.get("confidence","?")}] {_node(c["label"])}<br/><i>{ev}</i>"]')
    L.append("  end")
    L.append('  subgraph Inference["Derived inference"]')
    for x in lanes:
        L.append(f'    I{x["n"]}["{_node(x["inference"])}"]')
    L.append("  end")
    L.append('  subgraph Risk["Reviewer question"]')
    for x in lanes:
        L.append(f'    R{x["n"]}["{_node(x["risk"])}"]')
    L.append("  end")
    L.append('  subgraph Evidence["Evidence needed to close"]')
    for x in lanes:
        L.append(f'    E{x["n"]}["{_node(" · ".join(x["evidence"]))}"]')
    L.append("  end")
    for x in lanes:
        n = x["n"]
        L.append(f"  C{n} --> I{n} --> R{n} --> E{n}")
    # dark text on the light pastel fills, so nodes stay readable under either mermaid theme
    L += ["  classDef clue fill:#eef3f9,stroke:#6f7f91,color:#1f3a5f;",
          "  classDef infer fill:#fff7e6,stroke:#b98500,color:#6b4e00;",
          "  classDef risk fill:#fbe9e9,stroke:#b02a2a,color:#7a1f1f;",
          "  classDef evidence fill:#e6f4ea,stroke:#1e7d34,color:#14532d;"]
    ids = lambda p: ",".join(f"{p}{x['n']}" for x in lanes)
    L.append(f"  class {ids('C')} clue;")
    L.append(f"  class {ids('I')} infer;")
    L.append(f"  class {ids('R')} risk;")
    L.append(f"  class {ids('E')} evidence;")
    return "\n".join(L)


def build_prompt(module: str, clues: list[dict]) -> str:
    clue_json = json.dumps(clues, indent=2)
    return (
        f"You are assisting a FIPS 140-3 module reviewer for: {module}.\n\n"
        "Below is a DETERMINISTICALLY extracted set of clues from the module's CMVP "
        "certificate and Security Policy. For each clue, extend it into three tiers:\n"
        "  - Inference: what the disclosure does and does NOT let a reviewer conclude.\n"
        "  - Risk: why a reviewer should care (as a QUESTION or evidence gap).\n"
        "  - Evidence-to-close: the specific artifact that would resolve it (SBOM, "
        "config, signature-before-parse proof, reachability matrix, library id, etc.).\n\n"
        "HARD CONSTRAINTS:\n"
        "  - These are REVIEW PROMPTS and EVIDENCE GAPS, not vulnerability findings. Do "
        "not assert that the module is exploitable or insecure.\n"
        "  - Ground every node in the provided clues; do not invent facts not implied by them.\n"
        "  - Respect each clue's `confidence`: for 'low' clues (bare keyword hits — a "
        "protocol name may be a KDF, an OS mention may be out of boundary) phrase the "
        "inference as a possibility and make the FIRST evidence item 'confirm the clue "
        "itself'. Do not escalate a low-confidence clue into a strong risk.\n"
        "  - Output a Mermaid `flowchart LR` with subgraphs Clue/Inference/Risk/Evidence "
        "and edges Cn-->In-->Rn-->En, using the class styles for each tier.\n\n"
        f"CLUES:\n{clue_json}\n")


_GRAPH_MODEL = os.getenv("CMVP_GRAPH_MODEL", "claude-opus-4-8")


def _anthropic(prompt: str) -> str:
    """Live capable-model call for the reasoning tiers (opus-class by default)."""
    import anthropic
    client = anthropic.Anthropic()
    resp = client.messages.create(model=_GRAPH_MODEL, max_tokens=4096,
                                  messages=[{"role": "user", "content": prompt}])
    return "".join(b.text for b in resp.content if getattr(b, "type", None) == "text")


def validate_graph(mermaid: str, clues: list[dict]) -> tuple[bool, list[str]]:
    """Reliability gate for a generated four-tier graph. The model output is only
    accepted if it is STRUCTURALLY faithful to the deterministic clue set: every
    clue Cn expands to exactly In/Rn/En with the Cn-->In-->Rn-->En chain, and no
    node references a clue id that was not extracted (no invented findings)."""
    ids = set(re.findall(r"\b([CIRE]\d+)\b", mermaid))
    nums = {c["id"][1:] for c in clues}
    issues = []
    for n in nums:
        for tier in "CIRE":
            if f"{tier}{n}" not in ids:
                issues.append(f"missing {tier}{n}")
    for nid in ids:
        if nid[1:] not in nums:
            issues.append(f"orphan node {nid} (no matching clue)")
    for n in nums:
        for a, b in (("C", "I"), ("I", "R"), ("R", "E")):
            if not re.search(rf"\b{a}{n}\b\s*--?>?\s*\|?[^\n]*\b{b}{n}\b", mermaid):
                issues.append(f"missing edge {a}{n}->{b}{n}")
    return (not issues), issues


def _persist_graph(path: str, mermaid: str) -> None:
    """Write the validated 4-tier graph into the record's securityPolicy.reviewGraph
    so render_html reads it. This is the bridge that was missing: previously the
    graph landed in an orphan sidecar the renderer never opened."""
    record = json.load(open(path))
    sp = record.get("securityPolicy")
    if sp is None:
        record["securityPolicy"] = sp = {}
    sp["reviewGraph"] = mermaid
    with open(path, "w") as fh:
        json.dump(record, fh, indent=2, ensure_ascii=False)


def run_graph(record: dict, path: str, out: str | None, write: bool = True):
    """Full 4-tier graph via the capable-model pass, validated then persisted."""
    module = record.get("certificate", {}).get("moduleName", path)
    clues = extract_clues(record, _sidecar_text(record, path))
    if not clues:
        print("no clues extracted; nothing to reason over")
        return 1
    mermaid = _anthropic(build_prompt(module, clues))
    mermaid = re.sub(r"^```[a-z]*\n?|\n?```$", "", mermaid.strip())
    ok, issues = validate_graph(mermaid, clues)
    print(f"{module}: {len(clues)} clues -> graph validation {'PASS' if ok else 'REJECTED'}")
    for i in issues:
        print("   -", i)
    if ok:
        open(out or (os.path.splitext(path)[0] + ".review-graph.mermaid"), "w").write(mermaid)
        if write:
            _persist_graph(path, mermaid)
            print("wrote securityPolicy.reviewGraph into", path)
    return 0 if ok else 2


def run_lanes(record: dict, path: str, write: bool):
    """Deterministic 4-tier graph (no model). Validated with the same gate, then
    persisted into the record so the reviewer surface is never clue-only."""
    module = record.get("certificate", {}).get("moduleName", path)
    clues = extract_clues(record, _sidecar_text(record, path))
    if not clues:
        print("no clues extracted; nothing to reason over")
        return 1
    mermaid = to_mermaid_lanes(module, clues)
    ok, issues = validate_graph(mermaid, clues)
    if not ok:
        print(f"{module}: deterministic lanes FAILED self-check:", issues)
        return 2
    if write:
        _persist_graph(path, mermaid)
        print(f"{module}: wrote deterministic 4-tier reviewGraph into {path}")
    else:
        print(mermaid)
    return 0


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("record")
    ap.add_argument("--mermaid", action="store_true", help="clue tier only (debug)")
    ap.add_argument("--lanes", action="store_true", help="deterministic 4-tier graph (no model)")
    ap.add_argument("--prompt", action="store_true")
    ap.add_argument("--graph", action="store_true", help="full 4-tier graph via a capable model")
    ap.add_argument("--write", action="store_true", help="persist the graph into securityPolicy.reviewGraph")
    ap.add_argument("--out")
    args = ap.parse_args(argv)

    record = json.load(open(args.record))
    module = record.get("certificate", {}).get("moduleName", args.record)
    clues = extract_clues(record, _sidecar_text(record, args.record))

    if args.graph:
        return run_graph(record, args.record, args.out, write=args.write)
    if args.lanes:
        return run_lanes(record, args.record, write=args.write)
    if args.mermaid:
        print(to_mermaid_cluetier(module, clues))
    elif args.prompt:
        print(build_prompt(module, clues))
    else:
        print(f"{module}: {len(clues)} deterministic clue(s)")
        for c in clues:
            print(f"\n  [{c['id']}] {c['label']}")
            for e in c["evidence"]:
                print(f"       · {e}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
